### ISSUE TITLE
Provide Example of messaging API using html

### ISSUE THREAD

**Issue by fbradyirl** [CiscoDevNet/webexteamssdk#75]
I will assign this one to myself!

In [rebranding the Home Assistant Webex Teams integration](https://github.com/home-assistant/home-assistant/pull/21938), I decided to enhance it a little by posting the messages using the `html` parameter. E,g,

```python
from webexteamssdk import WebexTeamsAPI

client = WebexTeamsAPI(access_token=token)
message = "<strong>Build 0.89.6 is unstable.</strong>"
client.messages.create(roomId=room, html=message)
```

This gets powerful when you know which html tags are supported.

![Screenshot 2019-03-12 at 11 33 48](https://user-images.githubusercontent.com/254309/54197006-bdc63480-44ba-11e9-9b09-03596fdb57da.png)

Here is the message format for those:

```yaml
- alias: "Plain Test no HTML"
  trigger:
    - platform: webhook
      webhook_id: new_version
  action:
    service: notify.cisco_webex_teams_notify
    data:
      message: "This is a pretty plain old message."

      
- alias: "Notify On Build Failing"
  trigger:
    - platform: webhook
      webhook_id: build_failed
  action:
    service: notify.cisco_webex_teams_notify
    data:
      message: "<blockquote class=danger>Build 0.89.5 compile failed."


- alias: "Notify On Build Unstable"
  trigger:
    - platform: webhook
      webhook_id: build_unstable
  action:
    service: notify.cisco_webex_teams_notify
    data:
      title: "<strong>Build 0.89.6 is unstable.</strong>"
      message: "<blockquote class=warning>Version 0.89.6 failed verifications.
      
      <ul>
        <li> test_osx
        <li> test_win_lint

        <li>... and 4 more.
      </ul>
      <p><@personEmail:sparkbotjeeves@sparkbot.io></p>
      <p><small><i>View <a href='https://demo/testReport/'>Test Report</a></i></small><br></p>
      "


- alias: "Notify On Build Passing"
  trigger:
    - platform: webhook
      webhook_id: build_passed
  action:
    service: notify.cisco_webex_teams_notify
    data:
      title: "<strong>✅ Version 0.89.7 passed all tests and deployed to production!</strong>"
      message: "<blockquote class=info>Version 0.89.7 passed all verifications.
      
      <ul>
        <li> test_cov
        <li> test_osx
        <li> test_win
        <li> test_linux
        <li>... and 45 more.
      </ul>
      "
```
